### ISSUE TITLE
phymem_usage not available in newer versions of psutil

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#16]
swsearch.py uses psutil.phymem_usage which has been deprecated

Traceback (most recent call last):
  File "/app/bin/swsearch.py", line 138, in <module>
    main(sys.argv[1:])
  File "/app/bin/swsearch.py", line 135, in main
    search_container(parse_arguments())
  File "/app/bin/swsearch.py", line 74, in search_container
    memavail=psutil.phymem_usage().available
AttributeError: 'module' object has no attribute 'phymem_usage'

**Comment by jmkatcher** [comment]
Checked in a version using virtual_memory instead.
