### ISSUE TITLE
error in swrm.py

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#19]
this happens only with this specific container

root@lxdtest1:~# swc rm /test12
using account AUTH_Swift__ADM_SciComp:
...swrm.py -c test12 -p 
Warning: no prefix / pseudo folder entered - will delete container
    checking swift folder /test12/ ...
    checking size of /test12/ ... 
Traceback (most recent call last):
  File "/usr/local/bin/swrm.py", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.5/dist-packages/swift_commander/swrm.py", line 76, in main
    c.delete_container(args.container)
  File "/usr/local/lib/python3.5/dist-packages/swiftclient/client.py", line 1653, in delete_container
    response_dict=response_dict)
  File "/usr/local/lib/python3.5/dist-packages/swiftclient/client.py", line 1565, in _retry
    service_token=self.service_token, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/swiftclient/client.py", line 1059, in delete_container
    http_response_content=body)
swiftclient.exceptions.ClientException: Container DELETE failed: https://tin.fhcrc.org/v1/AUTH_Swift__ADM_SciComp/test12 409 Conflict  [first 60 chars of response] b'<html><h1>Conflict</h1><p>There was a conflict when trying t'

**Comment by dirkpetersen** [comment]
cannot reproduce
