### ISSUE TITLE
swhashcomp: fix python3 error "Unicode-objects must be encoded"

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#5]
petersen@rhino03:~/bin$ swhashcomp.py --locfile /home/petersen/sc/data/dna-test/dna-256MB --container=test_bundle --obj fld1.bundle.tar.gz
comparing swift object test_bundle/fld1.bundle.tar.gz with file /home/petersen/sc/data/dna-test/dna-256MB...
Traceback (most recent call last):
  File "/app/bin/swhashcomp.py", line 100, in <module>
    sys.exit(main())
  File "/app/bin/swhashcomp.py", line 29, in main
    hasher = hashlib.md5(f.read())
TypeError: Unicode-objects must be encoded before hashing

**Comment by dirkpetersen** [comment]
now fixed
