### ISSUE TITLE
swhashcomp: fix python3 error:  the JSON object must be str, not 'bytes'

### ISSUE THREAD

**Issue by dirkpetersen** [FredHutch/swift-commander#6]
petersen@rhino03:~/bin$ swhashcomp.py --locfile /home/petersen/sc/data/dna-test/dna-256MB --container=test --obj=dna-256MB
comparing swift object test/dna-256MB with file /home/petersen/sc/data/dna-test/dna-256MB...
True
Traceback (most recent call last):
  File "/app/bin/swhashcomp.py", line 100, in <module>
    sys.exit(main())
  File "/app/bin/swhashcomp.py", line 26, in main
    is_valid = check_manifest(body, f, md5all)
  File "/app/bin/swhashcomp.py", line 48, in check_manifest
    manifest = json.loads(manifest)
  File "/app/python3/3.4.1/lib/python3.4/json/**init**.py", line 312, in loads
    s.**class**.**name**))
TypeError: the JSON object must be str, not 'bytes'

**Comment by dirkpetersen** [comment]
now fixed
